load: STARTUP
main: com.zp4rker.bukkot.Bukkot
api-version: ${mcVersion}
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:2.0.21
  - org.jetbrains.kotlin:kotlin-reflect:2.0.21
  - org.jetbrains.kotlinx:kotlinx-coroutines-core:1.9.0

name: Bukkot
version: ${version}
description: ${description}
author: zp4rker
website: https://github.com/zp4rker/bukkot
